Module1 task3
htmlacademy-ecmascript/610873-cinemaddict-15 pull request #3
Opened 2021-08-01 22:55 UTC by EvilSight

2021-08-01 22:56 UTC, EvilSight commented
Были проблемы с "путями" от 2 до 10 ошибки))))

2021-08-02 06:40 UTC, balesniy requested changes

2021-08-02 06:40 UTC, balesniy commented on public/index.html
> +<script src="/public/bundle.js"></script>
путь нужно поправить

2021-08-02 06:40 UTC, balesniy commented on src/main.js
> +const TASK_COUNT = 5;
фильмы?

2021-08-02 06:40 UTC, balesniy commented on src/main.js
> +  render(films, createFilmsListExtraTemplate() < 'beforeend');
похоже опечатка

2021-08-02 06:40 UTC, balesniy commented on src/main.js
> +// Потерял мысль по поводу createFilmsListExtraTemplate не понимаю какую функцию или метод нужно использовать далее
в блоки "экстра" нужно отрисовать по 2 карточки фильмов

2021-08-02 19:20 UTC, merged