Module2 task1
htmlacademy-ecmascript/610873-cinemaddict-15 pull request #4
Opened 2021-08-15 20:44 UTC by EvilSight

2021-08-16 15:49 UTC, balesniy requested changes
- все очень неплохо, нужно поработать с именованием параметров и комментариями в попап
- генерация данных дублируется, нужно оставить один вариант

2021-08-16 15:49 UTC, balesniy commented on package.json
> +    "dayjs": "1.9.5",
оставь одну запись

2021-08-16 15:49 UTC, balesniy commented on view/user-profile.js
> +export const createSiteProfileTemplate = () => (
перепишите функцию по созданию шаблона, чтобы она на вход принимала данные.

2021-08-16 15:49 UTC, balesniy commented on view/statistics.js
> +export const createStatisticsTemplate = (param) => (
параметру нужно дать более наглядное название, весь массив сюда можно не передавать

2021-08-16 15:49 UTC, balesniy commented on view/site-nav.js
> +  param.forEach((objCard) => {
функцию по подготовке данных нужно вынести из компонента, параметрам дать наглядные названия

2021-08-16 15:49 UTC, balesniy commented on view/films-sort.js
>      <li><a href="#" class="sort__button sort__button--active">Sort by rating</a></li>
текущую активную сортировку нужно передать параметром

2021-08-16 15:49 UTC, balesniy commented on view/popup.js
>            <button type="button" class="film-details__control-button film-details__control-button--watchlist" id="watchlist" name="watchlist">Add to watchlist</button>
тут нужно поставить классы от статуса фильма, `film-details__control-button--active`

2021-08-16 15:49 UTC, balesniy commented on view/popup.js
>            <h3 class="film-details__comments-title">Comments <span class="film-details__comments-count">4</span></h3>
количество и список комментариев нужно взять из данных

2021-08-16 15:49 UTC, balesniy commented on src/utils/utils.js
> +export const getRandomInt = (min, max) => Math.floor(Math.random() * (max - min + 1) + min);
повторяет getRandomPositiveInteger

2021-08-16 15:49 UTC, balesniy commented on src/utils/utils.js
> +export const RATED_COUNT = 8;
все константы можно собрать в const.js

2021-08-16 15:49 UTC, balesniy commented on src/mock/film-card.js
> +const TitleAndPoster = () => {
функции нужен глагол в названии и строчная первая буква

2021-08-16 15:49 UTC, balesniy commented on src/mock/film-card.js
> +  alreadyWatched ? watchingDate = getRandomDate(-7, -12, -2) : null;
тернарный без присвоения нарушает критерии, тут или обычный if или результат нужно присвоить в переменную, см https://learn.javascript.ru/ifelse#netraditsionnoe-ispolzovanie

2021-08-16 15:49 UTC, balesniy commented on src/mock/film-card.js
> +    runtime: getRandomPositiveInteger(20, 280),
если это в минутах то хорошо, в шаблонах нужно добавить функцию по форматированию значения в часы

2021-08-16 15:49 UTC, balesniy commented on src/mock/film-card.js
> +const TitlePosterPairs = {
тут не нужна заглавная, можно КАПСОМ_ВСЕ_КОНСТАНТЫ

2021-08-16 15:49 UTC, balesniy commented on src/mock/data-card.js
> +const generateObject = () => (
повторяет mock/film-card.js

2021-08-16 15:49 UTC, balesniy commented on src/main.js
> +const linkCommentElement = document.querySelectorAll('.film-card__comments');
массивы просят назвать во множественном числе

2021-08-16 15:49 UTC, balesniy commented on src/main.js
> +    closePopup.addEventListener('click', () => {
анонимные обработчики копятся на кнопке

2021-08-16 15:49 UTC, balesniy commented on src/main.js
> +const titleExtra = [{ title: 'Top rated' }, { title: 'Most commented' }];
массиву просят множественное число в названии

2021-08-16 15:49 UTC, balesniy commented on src/main.js
> +for (let i = 0; i < 2; i++) {
2 похожа на магическое число, ей нужно наглядное название или совсем избавиться от цикла

2021-08-16 15:49 UTC, balesniy commented on src/main.js
> +  .slice(0, 2);
2 в константы

2021-08-18 11:28 UTC, EvilSight commented on src/main.js
> +const titleExtra = [{ title: 'Top rated' }, { title: 'Most commented' }];
titlesExtra

2021-08-20 06:43 UTC, balesniy requested changes
стало сильно лучше, направление верное.

2021-08-20 06:43 UTC, balesniy commented on view/button-more.js
> +export const createButtonMoreTemplate = (buttonMore) => (
тут лишний параметр, в кнопке текст не меняется

2021-08-20 06:43 UTC, balesniy commented on view/films-card.js
> +export const createFilmCardTemplate = (filmCard) => {
👍

2021-08-20 06:43 UTC, balesniy commented on view/films-list.js
> +export const createFilmListTemplate = (filmList) => (
тут не понял

2021-08-20 06:43 UTC, balesniy commented on view/films-sort.js
> +export const createSiteSortTemplate = (siteSort) => (
тут параметром должно быть название текущей активной сортировки, чтобы выставить sort__button--active

2021-08-20 06:43 UTC, balesniy commented on view/site-nav.js
> +  navigation.forEach((objCard) => {
тут нужно уточнить название параметра, "массив навигации" ? что именно хранится в этом массиве?

2021-08-20 06:43 UTC, balesniy commented on view/statistics.js
> +export const createStatisticsTemplate = (statistics) => (
в массиве не статистика, а если я правильно понял, то массив фильмов, тогда films или movies, но вообще компоненту весь массив не нужен, достаточно передать число

2021-08-20 06:43 UTC, balesniy commented on view/user-profile.js
> +export const createSiteProfileTemplate = (userProfile) => (
тут точнее будет userRating

2021-08-21 08:23 UTC, balesniy requested changes

2021-08-21 08:23 UTC, balesniy commented on src/main.js
> +const navFilmsElement = document.querySelectorAll('.main-navigation__item');
массивы просят назвать во множественном числе

2021-08-21 08:23 UTC, balesniy commented on view/films-sort.js
> +    <li><a href="#" class="sort__button sort__button--active">${currentActiveSort}Sort by rating</a></li>
для текущей сортировки нужно поставить класс sort__button--active, то есть в параметр придет например "by default" и значит для первого элемента списка нужно установить класс

2021-08-22 18:42 UTC, balesniy requested changes

2021-08-22 18:42 UTC, balesniy commented on view/site-nav.js
> +  navigation.forEach((objCard) => {
все еще актуально

2021-08-22 18:42 UTC, balesniy commented on view/popup.js
>            <button type="button" class="film-details__control-button film-details__control-button--watchlist" id="watchlist" name="watchlist">Add to watchlist</button>
все еще актуально

2021-08-22 18:42 UTC, balesniy commented on view/popup.js
>            <h3 class="film-details__comments-title">Comments <span class="film-details__comments-count">4</span></h3>
все еще актуально

2021-08-22 18:42 UTC, balesniy commented on src/utils/utils.js
> +  return Math.floor(lower + Math.random() * (upper - lower + 1));
повторяет getRandomInt

2021-08-22 18:42 UTC, balesniy commented on src/mock/film-card.js
> +  } else {
лишний блок else

2021-08-22 18:42 UTC, balesniy commented on src/main.js
> +    closePopup.addEventListener('click', () => {
все еще актуально

2021-08-23 19:49 UTC, balesniy commented on view/popup.js
> +          <h3 class="film-details__comments-title">Comments <span class="film-details__comments-count">${countComments}</span></h3>
список комментариев нужно заполнить из данных

2021-08-28 15:34 UTC, balesniy commented on view/popup.js
> +  const filterItemsTemplate = comments.map((comment) => createCommentPopupTemplate(comment)).join('');
переменной нужно дать более наглядное имя

2021-08-28 15:35 UTC, balesniy commented on view/popup.js
>              <div class="film-details__emoji-list">
список инпутов имеет смысл отрисовать в цикле

2021-08-28 15:35 UTC, merged